export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const PURCHASED_ITEM = 'PURCHASED_ITEM';
export const RETURN_TO_PURCHASED_LIST = 'RETURN_TO_PURCHASED_LIST';
export const DELETE_ITEM = 'DELETE_ITEM';